
[services]
[services.backend]
name = "backend"
start = "python ai/server.py"
setup = "pip install -r requirements.txt"

[services.frontend]
name = "frontend"
start = "serve -s build"
setup = """
      npm install
      npm run build
    """

[deployments]
[deployments.production]
services = ["backend", "frontend"]
