
[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["...", "python", "nodejs"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["npm install", "pip install -r requirements.txt"]

[deploy]
startCommand = "python ai/server.py"
