
[services]
[services.backend]
name = "backend"
start = "python ai/server.py"
setup = "pip install -r requirements.txt"

[services.frontend]
name = "frontend"
start = "npm run dev"
setup = "npm install"

[deployments]
[deployments.production]
services = ["backend", "frontend"]
